# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  opengl_tutorial_config = debug

else ifeq ($(config),release)
  opengl_tutorial_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := opengl-tutorial

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

opengl-tutorial:
ifneq (,$(opengl_tutorial_config))
	@echo "==== Building opengl-tutorial ($(opengl_tutorial_config)) ===="
	@${MAKE} --no-print-directory -C . -f opengl-tutorial.make config=$(opengl_tutorial_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f opengl-tutorial.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   opengl-tutorial"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"